{% set name = "demumble" %}
{% set version = "1.2.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://github.com/nico/demumble/archive/refs/tags/v{{ version }}.tar.gz
    sha256: 5546681f1997da4363eba464be49c1cc0af865d335e5e0990097ace04c37bc9a

build:
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - ninja
    - pkg-config

test:
  commands:
    - demumble --help

about:
  home: https://github.com/nico/demumble
  summary: A better c++filt and a better undname.exe, in one binary.
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - xhochy
