{% set name = "demumble" %}
{% set version = "1.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://github.com/nico/demumble/archive/refs/tags/v{{ version }}.tar.gz
    sha256: 29501fbd5522820a1672aea0292105b8706899e4e4b283ff51c126f79b3b2c41

build:
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
    - cmake
    - ninja
    - pkg-config

test:
  commands:
    - demumble --help

about:
  home: https://github.com/nico/demumble
  summary: A better c++filt and a better undname.exe, in one binary.
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - xhochy
